# dic_spawnre.py

genre_mapping = {
    'A00': {'Hex': '0x00', 'Genre': 'rock'},
    'A01': {'Hex': '0x01', 'Genre': 'classic rock'},
    'A02': {'Hex': '0x02', 'Genre': 'alternative rock'},
    'A03': {'Hex': '0x03', 'Genre': 'indie rock'},
    'A04': {'Hex': '0x04', 'Genre': 'folk rock'},
    'A05': {'Hex': '0x05', 'Genre': 'mellow rock'},
    'A06': {'Hex': '0x06', 'Genre': 'acoustic rock'},
    'A07': {'Hex': '0x07', 'Genre': 'piano rock'},
    'A08': {'Hex': '0x08', 'Genre': 'pop rock'},
    'A09': {'Hex': '0x09', 'Genre': 'hard rock'},
    'A10': {'Hex': '0x0A', 'Genre': 'grunge'},
    'A11': {'Hex': '0x0B', 'Genre': 'metal'},
    'A12': {'Hex': '0x0C', 'Genre': 'hardcore'},
    'A13': {'Hex': '0x0D', 'Genre': 'emo'},
    'A14': {'Hex': '0x0E', 'Genre': 'jam band'},
    'A15': {'Hex': '0x0F', 'Genre': 'ska punk'},
    'A16': {'Hex': '0x10', 'Genre': 'punk'},
    'A17': {'Hex': '0x11', 'Genre': 'surf rock'},
    'A18': {'Hex': '0x12', 'Genre': 'funk rock'},
    'A19': {'Hex': '0x13', 'Genre': 'rock & roll'},
    'A20': {'Hex': '0x14', 'Genre': 'country rock'},
    'A21': {'Hex': '0x15', 'Genre': 'blues rock'},
    'A22': {'Hex': '0x16', 'Genre': 'rap rock'},
    'A23': {'Hex': '0x17', 'Genre': 'rock electronica'},
    'B00': {'Hex': '0x18', 'Genre': 'folk'},
    'B01': {'Hex': '0x19', 'Genre': 'singer-songwriter'},
    'B02': {'Hex': '0x1A', 'Genre': 'world music'},
    'B03': {'Hex': '0x1B', 'Genre': ''},
    'B04': {'Hex': '0x1C', 'Genre': ''},
    'B05': {'Hex': '0x1D', 'Genre': ''},
    'B06': {'Hex': '0x1E', 'Genre': 'acoustic folk'},
    'B07': {'Hex': '0x1F', 'Genre': 'piano folk'},
    'B08': {'Hex': '0x20', 'Genre': ''},
    'B09': {'Hex': '0x21', 'Genre': ''},
    'B10': {'Hex': '0x22', 'Genre': ''},
    'B11': {'Hex': '0x23', 'Genre': ''},
    'B12': {'Hex': '0x24', 'Genre': ''},
    'B13': {'Hex': '0x25', 'Genre': ''},
    'B14': {'Hex': '0x26', 'Genre': ''},
    'B15': {'Hex': '0x27', 'Genre': ''},
    'B16': {'Hex': '0x28', 'Genre': ''},
    'B17': {'Hex': '0x29', 'Genre': ''},
    'B18': {'Hex': '0x2A', 'Genre': ''},
    'B19': {'Hex': '0x2B', 'Genre': ''},
    'B20': {'Hex': '0x2C', 'Genre': ''},
    'B21': {'Hex': '0x2D', 'Genre': ''},
    'B22': {'Hex': '0x2E', 'Genre': ''},
    'B23': {'Hex': '0x2F', 'Genre': ''},
    'C00': {'Hex': '0x30', 'Genre': 'pop'},
    'C01': {'Hex': '0x31', 'Genre': ''},
    'C02': {'Hex': '0x32', 'Genre': ''},
    'C03': {'Hex': '0x33', 'Genre': 'indie pop'},
    'C04': {'Hex': '0x34', 'Genre': ''},
    'C05': {'Hex': '0x35', 'Genre': ''},
    'C06': {'Hex': '0x36', 'Genre': ''},
    'C07': {'Hex': '0x37', 'Genre': ''},
    'C08': {'Hex': '0x38', 'Genre': ''},
    'C09': {'Hex': '0x39', 'Genre': ''},
    'C10': {'Hex': '0x3A', 'Genre': ''},
    'C11': {'Hex': '0x3B', 'Genre': ''},
    'C12': {'Hex': '0x3C', 'Genre': ''},
    'C13': {'Hex': '0x3D', 'Genre': ''},
    'C14': {'Hex': '0x3E', 'Genre': ''},
    'C15': {'Hex': '0x3F', 'Genre': ''},
    'C16': {'Hex': '0x40', 'Genre': 'pop punk'},
    'C17': {'Hex': '0x41', 'Genre': ''},
    'C18': {'Hex': '0x42', 'Genre': ''},
    'C19': {'Hex': '0x43', 'Genre': ''},
    'C20': {'Hex': '0x44', 'Genre': ''},
    'C21': {'Hex': '0x45', 'Genre': ''},
    'C22': {'Hex': '0x46', 'Genre': ''},
    'C23': {'Hex': '0x47', 'Genre': ''},
    'D00': {'Hex': '0x48', 'Genre': 'jazz'},
    'D01': {'Hex': '0x49', 'Genre': 'vocal jazz'},
    'D02': {'Hex': '0x4A', 'Genre': 'swing'},
    'D03': {'Hex': '0x4B', 'Genre': ''},
    'D04': {'Hex': '0x4C', 'Genre': ''},
    'D05': {'Hex': '0x4D', 'Genre': ''},
    'D06': {'Hex': '0x4E', 'Genre': ''},
    'D07': {'Hex': '0x4F', 'Genre': ''},
    'D08': {'Hex': '0x50', 'Genre': 'jazz pop'},
    'D09': {'Hex': '0x51', 'Genre': ''},
    'D10': {'Hex': '0x52', 'Genre': ''},
    'D11': {'Hex': '0x53', 'Genre': ''},
    'D12': {'Hex': '0x54', 'Genre': ''},
    'D13': {'Hex': '0x55', 'Genre': ''},
    'D14': {'Hex': '0x56', 'Genre': ''},
    'D15': {'Hex': '0x57', 'Genre': ''},
    'D16': {'Hex': '0x58', 'Genre': ''},
    'D17': {'Hex': '0x59', 'Genre': ''},
    'D18': {'Hex': '0x5A', 'Genre': ''},
    'D19': {'Hex': '0x5B', 'Genre': ''},
    'D20': {'Hex': '0x5C', 'Genre': ''},
    'D21': {'Hex': '0x5D', 'Genre': ''},
    'D22': {'Hex': '0x5E', 'Genre': ''},
    'D23': {'Hex': '0x5F', 'Genre': ''},
    'E00': {'Hex': '0x60', 'Genre': 'reggae'},
    'E01': {'Hex': '0x61', 'Genre': 'dub'},
    'E02': {'Hex': '0x62', 'Genre': ''},
    'E03': {'Hex': '0x63', 'Genre': ''},
    'E04': {'Hex': '0x64', 'Genre': ''},
    'E05': {'Hex': '0x65', 'Genre': ''},
    'E06': {'Hex': '0x66', 'Genre': ''},
    'E07': {'Hex': '0x67', 'Genre': ''},
    'E08': {'Hex': '0x68', 'Genre': ''},
    'E09': {'Hex': '0x69', 'Genre': ''},
    'E10': {'Hex': '0x6A', 'Genre': ''},
    'E11': {'Hex': '0x6B', 'Genre': ''},
    'E12': {'Hex': '0x6C', 'Genre': ''},
    'E13': {'Hex': '0x6D', 'Genre': ''},
    'E14': {'Hex': '0x6E', 'Genre': ''},
    'E15': {'Hex': '0x6F', 'Genre': 'ska'},
    'E16': {'Hex': '0x70', 'Genre': ''},
    'E17': {'Hex': '0x71', 'Genre': ''},
    'E18': {'Hex': '0x72', 'Genre': ''},
    'E19': {'Hex': '0x73', 'Genre': ''},
    'E20': {'Hex': '0x74', 'Genre': ''},
    'E21': {'Hex': '0x75', 'Genre': ''},
    'F00': {'Hex': '0x76', 'Genre': 'R&B'},
    'F01': {'Hex': '0x77', 'Genre': 'soul'},
    'F02': {'Hex': '0x78', 'Genre': 'gospel'},
    'F03': {'Hex': '0x79', 'Genre': ''},
    'F04': {'Hex': '0x7A', 'Genre': ''},
    'F05': {'Hex': '0x7B', 'Genre': ''},
    'F06': {'Hex': '0x7C', 'Genre': ''},
    'F07': {'Hex': '0x7D', 'Genre': ''},
    'F08': {'Hex': '0x7E', 'Genre': ''},
    'F09': {'Hex': '0x7F', 'Genre': ''},
    'F10': {'Hex': '0x80', 'Genre': ''},
    'F11': {'Hex': '0x81', 'Genre': ''},
    'F12': {'Hex': '0x82', 'Genre': ''},
    'F13': {'Hex': '0x83', 'Genre': ''},
    'F14': {'Hex': '0x84', 'Genre': ''},
    'F15': {'Hex': '0x85', 'Genre': ''},
    'F16': {'Hex': '0x86', 'Genre': ''},
    'F17': {'Hex': '0x87', 'Genre': ''},
    'F18': {'Hex': '0x88', 'Genre': 'funk'},
    'F19': {'Hex': '0x89', 'Genre': ''},
    'F20': {'Hex': '0x8A', 'Genre': ''},
    'F21': {'Hex': '0x8B', 'Genre': ''},
    'G00': {'Hex': '0x8C', 'Genre': 'country'},
    'G01': {'Hex': '0x8D', 'Genre': ''},
    'G02': {'Hex': '0x8E', 'Genre': ''},
    'G03': {'Hex': '0x8F', 'Genre': ''},
    'G04': {'Hex': '0x90', 'Genre': ''},
    'G05': {'Hex': '0x91', 'Genre': ''},
    'G06': {'Hex': '0x92', 'Genre': ''},
    'G07': {'Hex': '0x93', 'Genre': ''},
    'G08': {'Hex': '0x94', 'Genre': ''},
    'G09': {'Hex': '0x95', 'Genre': ''},
    'G10': {'Hex': '0x96', 'Genre': ''},
    'G11': {'Hex': '0x97', 'Genre': ''},
    'G12': {'Hex': '0x98', 'Genre': ''},
    'G13': {'Hex': '0x99', 'Genre': ''},
    'G14': {'Hex': '0x9A', 'Genre': ''},
    'G15': {'Hex': '0x9B', 'Genre': ''},
    'G16': {'Hex': '0x9C', 'Genre': ''},
    'G17': {'Hex': '0x9D', 'Genre': ''},
    'G18': {'Hex': '0x9E', 'Genre': ''},
    'G19': {'Hex': '0x9F', 'Genre': ''},
    'G20': {'Hex': '0xA0', 'Genre': ''},
    'G21': {'Hex': '0xA1', 'Genre': ''},
    'H00': {'Hex': '0xA2', 'Genre': 'blues'},
    'H01': {'Hex': '0xA3', 'Genre': ''},
    'H02': {'Hex': '0xA4', 'Genre': ''},
    'H03': {'Hex': '0xA5', 'Genre': ''},
    'H04': {'Hex': '0xA6', 'Genre': ''},
    'H05': {'Hex': '0xA7', 'Genre': ''},
    'H06': {'Hex': '0xA8', 'Genre': ''},
    'H07': {'Hex': '0xA9', 'Genre': ''},
    'H08': {'Hex': '0xAA', 'Genre': ''},
    'H09': {'Hex': '0xAB', 'Genre': ''},
    'H10': {'Hex': '0xAC', 'Genre': ''},
    'H11': {'Hex': '0xAD', 'Genre': ''},
    'H12': {'Hex': '0xAE', 'Genre': ''},
    'H13': {'Hex': '0xAF', 'Genre': ''},
    'H14': {'Hex': '0xB0', 'Genre': ''},
    'H15': {'Hex': '0xB1', 'Genre': ''},
    'H16': {'Hex': '0xB2', 'Genre': ''},
    'H17': {'Hex': '0xB3', 'Genre': ''},
    'H18': {'Hex': '0xB4', 'Genre': ''},
    'H19': {'Hex': '0xB5', 'Genre': ''},
    'H20': {'Hex': '0xB6', 'Genre': ''},
    'H21': {'Hex': '0xB7', 'Genre': ''},
    'I00': {'Hex': '0xB8', 'Genre': 'hip-hop'},
    'I01': {'Hex': '0xB9', 'Genre': ''},
    'I02': {'Hex': '0xBA', 'Genre': ''},
    'I03': {'Hex': '0xBB', 'Genre': ''},
    'I04': {'Hex': '0xBC', 'Genre': ''},
    'I05': {'Hex': '0xBD', 'Genre': ''},
    'I06': {'Hex': '0xBE', 'Genre': ''},
    'I07': {'Hex': '0xBF', 'Genre': ''},
    'I08': {'Hex': '0xC0', 'Genre': ''},
    'I09': {'Hex': '0xC1', 'Genre': ''},
    'I10': {'Hex': '0xC2', 'Genre': ''},
    'I11': {'Hex': '0xC3', 'Genre': ''},
    'I12': {'Hex': '0xC4', 'Genre': ''},
    'I13': {'Hex': '0xC5', 'Genre': ''},
    'I14': {'Hex': '0xC6', 'Genre': ''},
    'I15': {'Hex': '0xC7', 'Genre': ''},
    'I16': {'Hex': '0xC8', 'Genre': ''},
    'I17': {'Hex': '0xC9', 'Genre': ''},
    'I18': {'Hex': '0xCA', 'Genre': ''},
    'I19': {'Hex': '0xCB', 'Genre': ''},
    'I20': {'Hex': '0xCC', 'Genre': ''},
    'I21': {'Hex': '0xCD', 'Genre': ''},
    'I22': {'Hex': '0xCE', 'Genre': ''},
    'I23': {'Hex': '0xCF', 'Genre': ''},
    'J00': {'Hex': '0xD0', 'Genre': 'electronic'},
    'J01': {'Hex': '0xD1', 'Genre': 'EDM'},
    'J02': {'Hex': '0xD2', 'Genre': 'house'},
    'J03': {'Hex': '0xD3', 'Genre': 'techno'},
    'J04': {'Hex': '0xD4', 'Genre': 'disco'},
    'J05': {'Hex': '0xD5', 'Genre': ''},
    'J06': {'Hex': '0xD6', 'Genre': ''},
    'J07': {'Hex': '0xD7', 'Genre': ''},
    'J08': {'Hex': '0xD8', 'Genre': ''},
    'J09': {'Hex': '0xD9', 'Genre': ''},
    'J10': {'Hex': '0xDA', 'Genre': ''},
    'J11': {'Hex': '0xDB', 'Genre': ''},
    'J12': {'Hex': '0xDC', 'Genre': ''},
    'J13': {'Hex': '0xDD', 'Genre': ''},
    'J14': {'Hex': '0xDE', 'Genre': ''},
    'J15': {'Hex': '0xDF', 'Genre': ''},
    'J16': {'Hex': '0xE0', 'Genre': ''},
    'J17': {'Hex': '0xE1', 'Genre': ''},
    'J18': {'Hex': '0xE2', 'Genre': ''},
    'J19': {'Hex': '0xE3', 'Genre': ''},
    'J20': {'Hex': '0xE4', 'Genre': ''},
    'J21': {'Hex': '0xE5', 'Genre': ''},
    'J22': {'Hex': '0xE6', 'Genre': ''},
    'J23': {'Hex': '0xE7', 'Genre': ''},
    'K00': {'Hex': '0xE8', 'Genre': 'classical'},
    'K01': {'Hex': '0xE9', 'Genre': 'orchestral'},
    'K02': {'Hex': '0xEA', 'Genre': 'opera'},
    'K03': {'Hex': '0xEB', 'Genre': ''},
    'K04': {'Hex': '0xEC', 'Genre': ''},
    'K05': {'Hex': '0xED', 'Genre': ''},
    'K06': {'Hex': '0xEE', 'Genre': ''},
    'K07': {'Hex': '0xEF', 'Genre': 'piano'},
    'K08': {'Hex': '0xF0', 'Genre': ''},
    'K09': {'Hex': '0xF1', 'Genre': ''},
    'K10': {'Hex': '0xF2', 'Genre': ''},
    'K11': {'Hex': '0xF3', 'Genre': ''},
    'K12': {'Hex': '0xF4', 'Genre': ''},
    'K13': {'Hex': '0xF5', 'Genre': ''},
    'K14': {'Hex': '0xF6', 'Genre': ''},
    'K15': {'Hex': '0xF7', 'Genre': ''},
    'K16': {'Hex': '0xF8', 'Genre': ''},
    'K17': {'Hex': '0xF9', 'Genre': ''},
    'K18': {'Hex': '0xFA', 'Genre': ''},
    'K19': {'Hex': '0xFB', 'Genre': ''},
    'K20': {'Hex': '0xFC', 'Genre': ''},
    'K21': {'Hex': '0xFD', 'Genre': ''},
    'K22': {'Hex': '0xFE', 'Genre': ''},
    'K23': {'Hex': '0xFF', 'Genre': ''}
}
